Repository ansible-community/ansible-docsite, pull requests merged in 2023-12, with the labels that each got.

#320 dependabot python requirements
  .github/dependabot.yml
Labels: ci

#331 How ansible works page
  images/pages/network-automation-comparison.jpg
  pages/how-ansible-works.md
Labels: page migration

#334 Ansible community training page
  pages/ansible-community-training.md
Labels: page migration

#333 Galaxy page
  pages/galaxy.md
Labels: page migration

#323 [Blog] Port Kubernetes Meets Event-Driven Ansible to .md
  images/posts/kubernetes-meets-event-driven-ansible/Kubernetes + EDA.webp
  posts/2023/03/16/kubernetes-meets-event-driven-ansible.md
Labels: blog

#324 [Blog] Ansible data manipulation with a Filter
  posts/2023/08/03/ansible-data-manipulation-with-a-filter.md
Labels: blog

#325 [Blog] Port Getting Started with Event-Driven Ansible blog post to .md
  images/posts/getting-started-with-event-driven-ansible/event-driven-ansible.png
  images/posts/getting-started-with-event-driven-ansible/event-driven-automation.png
  images/posts/getting-started-with-event-driven-ansible/event-source.png
  images/posts/getting-started-with-event-driven-ansible/lifecycle-diagram.png
  posts/2022/10/19/getting-started-with-event-driven-ansible.md
Labels: blog

#326 [Blog] worked on blog posts from Ansible.com to the new website and convert …
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/constructed-combination-groups.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/create-new-inventory.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/create-new-project.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/create-new-source.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/host3-host-details.webp
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/image1.webp
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/inventory-details.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/inventory-group--combine-details.webp
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/inventory-group-host.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/inventory-output.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/inventory-source.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/job-group-output.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/new-constructed-inventory.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/setting-up-the-constructed-inventory.png
  images/posts/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4/target-group-details.webp
  posts/2023/06/29/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4.md
Labels: blog

#327 [Blog] Convert event driven Ansible blog post
  images/posts/event-driven-ansible-is-here/Certified-and-validated-content.webp
  images/posts/event-driven-ansible-is-here/event driven ansible is here.webp
  posts/2023/05/23/event-driven-ansible-is-here.md
Labels: blog

#332 AWX project page
  .codespellignorelines
  .codespellrc
  pages/awx.md
Labels: page migration

#342 Contact us page
  pages/contact-us.md
Labels: page migration
